name: forgejo
version: v1.4.0
slug: forgejo
description: Beyond coding. We forge. https://forgejo.org
url: https://gitlab.com/home-assistant-addons/home-assistant-forgejo
init: false
arch:
  - aarch64
  - amd64
map:
  - type: addon_config
    path: /var/lib/gitea/data
    read_only: false
ports:
  3000/tcp: 8001
  22/tcp: 2201
ingress: true
ingress_port: 3000
image: registry.gitlab.com/home-assistant-addons/home-assistant-forgejo
schema:
  arguments:
    - str
options:
  arguments:
    - -c /var/lib/gitea/data/conf/app.ini
